baseurl: /2017/vc/WG
groupid: 98922
charter: /2020/12/verifiable-credentials-wg-charter.html
wgname_lc: vc
wgname_uc: VC
mission: "The mission of the Verifiable Credentials (formerly known as Verifiable Claims) Working Group (VCWG) is to make expressing and exchanging credentials that have been verified by a third party easier and more secure on the Web. The Working Group is now in maintenance mode."

# theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules/

collections:
  minutes:
    output: true
    permalink: /Meetings/Minutes/:name
